import { describe, expect, it } from 'vitest'

import { buildDecisionSnapshot } from './decisionSnapshot.js'

describe('buildDecisionSnapshot', () => {
  it('captures the current decision context into a stable replay object', () => {
    const snapshot = buildDecisionSnapshot({
      capturedAt: '2026-04-14T05:00:08.000Z',
      canonicalMatchState: {
        matchId: 'event-1',
        source: {
          sourceKind: 'flashscore',
          matchUrl: 'https://www.flashscore.com/match/tennis/foo/bar/',
          sourcePageUrl: 'https://www.flashscore.com/match/tennis/foo/bar/?mid=abc',
        },
        competition: {
          tournamentName: 'ATP Monte Carlo',
          tournamentLabel: 'ATP Monte Carlo',
          tournamentPath: 'https://www.flashscore.com/tennis/atp-singles/monte-carlo/',
          round: 'Round of 32',
          bestOf: 3,
          tourType: 'ATP',
          gender: 'men',
          startTimeISO: '2026-04-12T18:00:00Z',
        },
        participants: {
          teamA: { name: 'Daniil Medvedev', shortName: 'Medvedev', code: 'MED', slug: 'medvedev', playerId: 'a1' },
          teamB: { name: 'Matteo Berrettini', shortName: 'Berrettini', code: 'BER', slug: 'berrettini', playerId: 'b1' },
        },
        status: {
          matchStatus: 'LIVE',
          statusText: 'Live',
          abnormalReason: 'none',
        },
        scoreboard: {
          setIndex: 2,
          setsWonA: 0,
          setsWonB: 1,
          currentSetGamesA: 4,
          currentSetGamesB: 3,
          currentGamePointsA: '30',
          currentGamePointsB: '30',
          isTiebreak: false,
        },
        serve: {
          raw: 'teamA',
          resolved: 'teamA',
          source: 'dom',
          confidence: 'high',
          syncState: 'synced',
        },
        quality: {
          matchIntegrity: 'ok',
        },
        stats: {
          acesA: 6,
          acesB: 4,
          firstServePercentageA: '62%',
          firstServePercentageB: '59%',
          pointsWonA: 72,
          pointsWonB: 69,
          firstServeWonA: '36/48',
          firstServeWonB: '34/50',
          secondServeWonA: '14/28',
          secondServeWonB: '12/24',
          servicePointsWonA: '63% (50/80)',
          servicePointsWonB: '62% (46/74)',
          firstServeReturnPointsWonA: '32% (16/50)',
          firstServeReturnPointsWonB: '25% (12/48)',
          secondServeReturnPointsWonA: '50% (12/24)',
          secondServeReturnPointsWonB: '50% (14/28)',
          returnPointsWonA: '35% (28/74)',
          returnPointsWonB: '33% (26/80)',
          serviceGamesWonA: 7,
          serviceGamesWonB: 6,
          returnGamesWonA: '22% (2/9)',
          returnGamesWonB: '11% (1/9)',
          breakPointsSavedA: '3/5',
          breakPointsSavedB: '2/4',
          breakPointsConvertedA: '2/4',
          breakPointsConvertedB: '1/5',
          breakPointsDisplayA: '2/4',
          breakPointsDisplayB: '1/5',
          doubleFaultsA: 2,
          doubleFaultsB: 1,
        },
        timestamps: {
          ingestedAt: '2026-04-13T19:00:00.000Z',
          scoreTimestamp: '2026-04-13T19:00:00.000Z',
          serveTimestamp: '2026-04-13T19:00:00.000Z',
          statsTimestamp: '2026-04-13T19:00:00.000Z',
        },
      },
      canonicalMarketState: {
        eventTicker: 'KXATP-123',
        marketTicker: 'KXATP-123-A',
        marketTitle: 'Will Medvedev beat Berrettini?',
        marketStatus: 'OPEN',
        prices: {
          yesBid: 57,
          yesAsk: 59,
          noBid: 41,
          noAsk: 43,
          lastPrice: 58,
        },
        liquidity: {
          volume: 600000,
        },
        timestamps: {
          marketTimestamp: '2026-04-14T05:00:00Z',
        },
      },
      kalshiMarketUrl: 'https://kalshi.com/markets/example',
      kalshiDisplayStats: {
        acesA: 6,
        acesB: 4,
        doubleFaultsA: 2,
        doubleFaultsB: 1,
        pointsWonA: 72,
        pointsWonB: 70,
        firstServeWonA: '36/48',
        firstServeWonB: '34/50',
        secondServeWonA: '15/28',
        secondServeWonB: '12/24',
        serviceGamesWonA: 7,
        serviceGamesWonB: 6,
        breakPointsDisplayA: '2/4',
        breakPointsDisplayB: '1/5',
      },
      resolvedStats: {
        acesA: { value: 6, source: 'kalshi_ui', confidence: 'high' },
        acesB: { value: 4, source: 'kalshi_ui', confidence: 'high' },
        doubleFaultsA: { value: 2, source: 'kalshi_ui', confidence: 'high' },
        doubleFaultsB: { value: 1, source: 'kalshi_ui', confidence: 'high' },
        firstServePercentageA: { value: '62%', source: 'flashscore', confidence: 'medium' },
        firstServePercentageB: { value: '59%', source: 'flashscore', confidence: 'medium' },
        pointsWonA: { value: 72, source: 'kalshi_ui', confidence: 'high' },
        pointsWonB: { value: 70, source: 'kalshi_ui', confidence: 'high' },
        firstServeWonA: { value: '36/48', source: 'kalshi_ui', confidence: 'high' },
        firstServeWonB: { value: '34/50', source: 'kalshi_ui', confidence: 'high' },
        secondServeWonA: { value: '15/28', source: 'kalshi_ui', confidence: 'high' },
        secondServeWonB: { value: '12/24', source: 'kalshi_ui', confidence: 'high' },
        servicePointsWonA: { value: '63% (50/80)', source: 'flashscore', confidence: 'medium' },
        servicePointsWonB: { value: '62% (46/74)', source: 'flashscore', confidence: 'medium' },
        firstServeReturnPointsWonA: { value: '32% (16/50)', source: 'flashscore', confidence: 'medium' },
        firstServeReturnPointsWonB: { value: '25% (12/48)', source: 'flashscore', confidence: 'medium' },
        secondServeReturnPointsWonA: { value: '50% (12/24)', source: 'flashscore', confidence: 'medium' },
        secondServeReturnPointsWonB: { value: '50% (14/28)', source: 'flashscore', confidence: 'medium' },
        returnPointsWonA: { value: '35% (28/74)', source: 'flashscore', confidence: 'medium' },
        returnPointsWonB: { value: '33% (26/80)', source: 'flashscore', confidence: 'medium' },
        serviceGamesWonA: { value: 7, source: 'kalshi_ui', confidence: 'high' },
        serviceGamesWonB: { value: 6, source: 'kalshi_ui', confidence: 'high' },
        returnGamesWonA: { value: '22% (2/9)', source: 'flashscore', confidence: 'medium' },
        returnGamesWonB: { value: '11% (1/9)', source: 'flashscore', confidence: 'medium' },
        breakPointsSavedA: { value: '3/5', source: 'flashscore', confidence: 'medium' },
        breakPointsSavedB: { value: '2/4', source: 'flashscore', confidence: 'medium' },
        breakPointsConvertedA: { value: '2/4', source: 'flashscore', confidence: 'medium' },
        breakPointsConvertedB: { value: '1/5', source: 'flashscore', confidence: 'medium' },
        breakPointsDisplayA: { value: '2/4', source: 'kalshi_ui', confidence: 'low' },
        breakPointsDisplayB: { value: '1/5', source: 'kalshi_ui', confidence: 'low' },
      },
      prematchBaseline: {
        source: 'market',
        complete: true,
        bestOf: 3,
        surface: 'clay',
        tourType: 'ATP',
        prematchFairProbA: 0.61,
        prematchFairProbB: 0.39,
        strengthBucketA: 'favorite',
        strengthBucketB: 'underdog',
        holdBaselineA: 0.82,
        holdBaselineB: 0.78,
        breakBaselineA: 0.24,
        breakBaselineB: 0.19,
      },
      pointRisk: {
        version: 'tennis-point-risk/v2-best-of-3',
        available: true,
        phase: 'non_tiebreak',
        stateLabel: '4-3 30-30',
        matchContext: null,
        serverContext: 'leader_serving',
        baseRisk: 'medium',
        contextAdjustment: 0,
        finalRisk: 'medium',
        structuralNote: null,
        marketBehavior: null,
        recommendation: null,
        machineCommand: 'WARN',
        stopTriggered: false,
        matchedRule: '4-3, 30-30, leader serving',
      },
      probabilityState: {
        version: 'tennis-probability-state/v1',
        available: true,
        baseline: {
          source: 'market',
          complete: true,
          bestOf: 3,
          surface: 'clay',
          tourType: 'ATP',
          prematchFairProbA: 0.61,
          prematchFairProbB: 0.39,
          strengthBucketA: 'favorite',
          strengthBucketB: 'underdog',
          holdBaselineA: 0.82,
          holdBaselineB: 0.78,
          breakBaselineA: 0.24,
          breakBaselineB: 0.19,
        },
        pFair: {
          version: 'p-fair/v1',
          point: { serverSide: 'teamA', pPointA: 0.64, pPointB: 0.36, source: 'derived' },
          game: { serverSide: 'teamA', pGameA: 0.72, pGameB: 0.28, pHoldServer: 0.72, pBreakReceiver: 0.28, source: 'derived' },
          set: { pSetA: 0.66, pSetB: 0.34, source: 'derived' },
          match: { pMatchA: 0.58, pMatchB: 0.42, source: 'derived' },
          anchor: {
            prematchFairProbA: 0.61,
            prematchFairProbB: 0.39,
            holdBaselineA: 0.82,
            holdBaselineB: 0.78,
            breakBaselineA: 0.24,
            breakBaselineB: 0.19,
          },
          diagnostics: {
            setIndex: 2,
            isTiebreak: false,
            pointScoreA: '30',
            pointScoreB: '30',
            gameScoreA: 4,
            gameScoreB: 3,
            riskRule: '4-3, 30-30, leader serving',
            integrity: 'ok',
          },
        },
        risk: {
          level: 'medium',
          machineCommand: 'WARN',
          matchedRule: '4-3, 30-30, leader serving',
          riskDrivers: ['rule:4-3, 30-30, leader serving'],
        },
        context: {
          phase: 'non_tiebreak',
          setContext: null,
          isTiebreak: false,
          isDecidingSet: false,
          abnormalReason: 'none',
          matchIntegrity: 'ok',
        },
      },
      tradePlan: {
        available: true,
        jumpPhase: true,
        tradeMode: 'maker_reversion_light',
        makerOnly: true,
        exposureAllowed: true,
        maxExposureTier: 'small',
        preferredSide: 'extreme_low_price_side',
        exitMode: 'price_recovery',
        forceExitOnStop: true,
        maxHoldSeconds: 30,
        summary: '跳变期轻仓 maker，优先抓低价一侧回补。',
        rationale: ['4-3, 30-30, leader serving', 'jump_phase', 'light_maker_reversion'],
      },
    })

    expect(snapshot.version).toBe('decision-snapshot/v1')
    expect(snapshot.urls.kalshiMarketUrl).toBe('https://kalshi.com/markets/example')
    expect(snapshot.match.teamA).toBe('Daniil Medvedev')
    expect(snapshot.sourceCoverage.flashscoreStatsAvailable).toBe(true)
    expect(snapshot.sourceCoverage.kalshiStatsAvailable).toBe(true)
    expect(snapshot.sourceCoverage.prematchBaselineAvailable).toBe(true)
    expect(snapshot.sourceCoverage.marketStateAvailable).toBe(true)
    expect(snapshot.stats.resolved.pointsWonB.value).toBe(70)
    expect(snapshot.pFair.match.pMatchA).toBe(0.58)
    expect(snapshot.fairVsMarket.available).toBe(true)
    expect(snapshot.marketEligibility.eligible).toBe(true)
    expect(snapshot.marketEligibility.metrics.askOverround).toBeCloseTo(0.02, 6)
    expect(snapshot.marketEligibility.metrics.marketAgeSeconds).toBeCloseTo(8, 6)
    expect(snapshot.liveDecision.action).toBe('ignore')
    expect(snapshot.liveDecision.marketEligible).toBe(true)
    expect(snapshot.fairVsMarket.edgeA.vsMid).toBeCloseTo(0, 6)
    expect(snapshot.tradePlan.tradeMode).toBe('maker_reversion_light')
    expect(snapshot.risk.matchedRule).toBe('4-3, 30-30, leader serving')
  })
})
